import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';

@Schema({
    timestamps: true
})
export class Article {
    @Prop() text: string;
    @Prop() author: string;
}

/**
 * Document will have _id generated by mongoose
 */
export type ArticleDocument = Article & Document;

export const ArticleSchema = SchemaFactory.createForClass(Article);
